[2023-06-25T06:10:28.015+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: spark_etl_minio_v14.spark_submit_task scheduled__2023-06-24T00:00:00+00:00 [queued]>
[2023-06-25T06:10:28.022+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: spark_etl_minio_v14.spark_submit_task scheduled__2023-06-24T00:00:00+00:00 [queued]>
[2023-06-25T06:10:28.022+0000] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-06-25T06:10:28.022+0000] {taskinstance.py:1283} INFO - Starting attempt 4 of 6
[2023-06-25T06:10:28.022+0000] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-06-25T06:10:28.031+0000] {taskinstance.py:1303} INFO - Executing <Task(SparkSubmitOperator): spark_submit_task> on 2023-06-24 00:00:00+00:00
[2023-06-25T06:10:28.035+0000] {standard_task_runner.py:55} INFO - Started process 27779 to run task
[2023-06-25T06:10:28.037+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'spark_etl_minio_v14', 'spark_submit_task', 'scheduled__2023-06-24T00:00:00+00:00', '--job-id', '234', '--raw', '--subdir', 'DAGS_FOLDER/spark_job_minio_v1.py', '--cfg-path', '/tmp/tmpwkrxelop']
[2023-06-25T06:10:28.038+0000] {standard_task_runner.py:83} INFO - Job 234: Subtask spark_submit_task
[2023-06-25T06:10:28.047+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:250: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2023-06-25T06:10:28.063+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/sqlalchemy.py:124: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  return not conf.get("database", "sql_alchemy_conn").startswith("mssql")

[2023-06-25T06:10:28.086+0000] {task_command.py:388} INFO - Running <TaskInstance: spark_etl_minio_v14.spark_submit_task scheduled__2023-06-24T00:00:00+00:00 [running]> on host a8d69ab09d2d
[2023-06-25T06:10:28.136+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=spark_etl_minio_v14
AIRFLOW_CTX_TASK_ID=spark_submit_task
AIRFLOW_CTX_EXECUTION_DATE=2023-06-24T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=4
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-06-24T00:00:00+00:00
[2023-06-25T06:10:28.143+0000] {base.py:73} INFO - Using connection ID 'spark_conn' for task execution.
[2023-06-25T06:10:28.144+0000] {spark_submit.py:341} INFO - Spark-Submit cmd: spark-submit --master spark://spark:7077 --jars local:///opt/bitnami/spark/jars/hadoop-aws-3.2.0.jar,            local:///opt/bitnami/spark/jars/aws-java-sdk-bundle-1.11.375.jar --name arrow-spark /opt/***/dags/spark_etl_spark_minio.py
[2023-06-25T06:10:29.100+0000] {spark_submit.py:492} INFO - WARNING: An illegal reflective access operation has occurred
[2023-06-25T06:10:29.101+0000] {spark_submit.py:492} INFO - WARNING: Illegal reflective access by org.apache.spark.unsafe.Platform (file:/opt/spark/jars/spark-unsafe_2.12-3.2.0.jar) to constructor java.nio.DirectByteBuffer(long,int)
[2023-06-25T06:10:29.101+0000] {spark_submit.py:492} INFO - WARNING: Please consider reporting this to the maintainers of org.apache.spark.unsafe.Platform
[2023-06-25T06:10:29.101+0000] {spark_submit.py:492} INFO - WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
[2023-06-25T06:10:29.101+0000] {spark_submit.py:492} INFO - WARNING: All illegal access operations will be denied in a future release
[2023-06-25T06:10:29.488+0000] {spark_submit.py:492} INFO - 23/06/25 06:10:29 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2023-06-25T06:10:29.679+0000] {spark_submit.py:492} INFO - Exception in thread "main" java.lang.IllegalArgumentException: java.net.URISyntaxException: Illegal character in scheme name at index 0:             local:
[2023-06-25T06:10:29.680+0000] {spark_submit.py:492} INFO - at org.apache.hadoop.fs.Path.initialize(Path.java:263)
[2023-06-25T06:10:29.680+0000] {spark_submit.py:492} INFO - at org.apache.hadoop.fs.Path.<init>(Path.java:221)
[2023-06-25T06:10:29.680+0000] {spark_submit.py:492} INFO - at org.apache.hadoop.fs.Path.<init>(Path.java:129)
[2023-06-25T06:10:29.680+0000] {spark_submit.py:492} INFO - at org.apache.hadoop.fs.Globber.doGlob(Globber.java:285)
[2023-06-25T06:10:29.680+0000] {spark_submit.py:492} INFO - at org.apache.hadoop.fs.Globber.glob(Globber.java:202)
[2023-06-25T06:10:29.680+0000] {spark_submit.py:492} INFO - at org.apache.hadoop.fs.FileSystem.globStatus(FileSystem.java:2124)
[2023-06-25T06:10:29.680+0000] {spark_submit.py:492} INFO - at org.apache.spark.util.DependencyUtils$.resolveGlobPath(DependencyUtils.scala:318)
[2023-06-25T06:10:29.680+0000] {spark_submit.py:492} INFO - at org.apache.spark.util.DependencyUtils$.$anonfun$resolveGlobPaths$2(DependencyUtils.scala:273)
[2023-06-25T06:10:29.680+0000] {spark_submit.py:492} INFO - at org.apache.spark.util.DependencyUtils$.$anonfun$resolveGlobPaths$2$adapted(DependencyUtils.scala:271)
[2023-06-25T06:10:29.681+0000] {spark_submit.py:492} INFO - at scala.collection.TraversableLike.$anonfun$flatMap$1(TraversableLike.scala:293)
[2023-06-25T06:10:29.681+0000] {spark_submit.py:492} INFO - at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:36)
[2023-06-25T06:10:29.681+0000] {spark_submit.py:492} INFO - at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:33)
[2023-06-25T06:10:29.681+0000] {spark_submit.py:492} INFO - at scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:38)
[2023-06-25T06:10:29.681+0000] {spark_submit.py:492} INFO - at scala.collection.TraversableLike.flatMap(TraversableLike.scala:293)
[2023-06-25T06:10:29.681+0000] {spark_submit.py:492} INFO - at scala.collection.TraversableLike.flatMap$(TraversableLike.scala:290)
[2023-06-25T06:10:29.681+0000] {spark_submit.py:492} INFO - at scala.collection.AbstractTraversable.flatMap(Traversable.scala:108)
[2023-06-25T06:10:29.681+0000] {spark_submit.py:492} INFO - at org.apache.spark.util.DependencyUtils$.resolveGlobPaths(DependencyUtils.scala:271)
[2023-06-25T06:10:29.681+0000] {spark_submit.py:492} INFO - at org.apache.spark.deploy.SparkSubmit.$anonfun$prepareSubmitEnvironment$4(SparkSubmit.scala:364)
[2023-06-25T06:10:29.681+0000] {spark_submit.py:492} INFO - at scala.Option.map(Option.scala:230)
[2023-06-25T06:10:29.681+0000] {spark_submit.py:492} INFO - at org.apache.spark.deploy.SparkSubmit.prepareSubmitEnvironment(SparkSubmit.scala:364)
[2023-06-25T06:10:29.682+0000] {spark_submit.py:492} INFO - at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:898)
[2023-06-25T06:10:29.682+0000] {spark_submit.py:492} INFO - at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:180)
[2023-06-25T06:10:29.682+0000] {spark_submit.py:492} INFO - at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:203)
[2023-06-25T06:10:29.682+0000] {spark_submit.py:492} INFO - at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:90)
[2023-06-25T06:10:29.682+0000] {spark_submit.py:492} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1043)
[2023-06-25T06:10:29.682+0000] {spark_submit.py:492} INFO - at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1052)
[2023-06-25T06:10:29.682+0000] {spark_submit.py:492} INFO - at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
[2023-06-25T06:10:29.682+0000] {spark_submit.py:492} INFO - Caused by: java.net.URISyntaxException: Illegal character in scheme name at index 0:             local:
[2023-06-25T06:10:29.683+0000] {spark_submit.py:492} INFO - at java.base/java.net.URI$Parser.fail(URI.java:2913)
[2023-06-25T06:10:29.683+0000] {spark_submit.py:492} INFO - at java.base/java.net.URI$Parser.checkChars(URI.java:3084)
[2023-06-25T06:10:29.683+0000] {spark_submit.py:492} INFO - at java.base/java.net.URI$Parser.checkChar(URI.java:3094)
[2023-06-25T06:10:29.683+0000] {spark_submit.py:492} INFO - at java.base/java.net.URI$Parser.parse(URI.java:3109)
[2023-06-25T06:10:29.683+0000] {spark_submit.py:492} INFO - at java.base/java.net.URI.<init>(URI.java:758)
[2023-06-25T06:10:29.683+0000] {spark_submit.py:492} INFO - at org.apache.hadoop.fs.Path.initialize(Path.java:260)
[2023-06-25T06:10:29.683+0000] {spark_submit.py:492} INFO - ... 26 more
[2023-06-25T06:10:29.741+0000] {taskinstance.py:1775} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 157, in execute
    self._hook.submit(self._application)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 423, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark://spark:7077 --jars local:///opt/bitnami/spark/jars/hadoop-aws-3.2.0.jar,            local:///opt/bitnami/spark/jars/aws-java-sdk-bundle-1.11.375.jar --name arrow-spark /opt/***/dags/spark_etl_spark_minio.py. Error code is: 1.
[2023-06-25T06:10:29.744+0000] {taskinstance.py:1321} INFO - Marking task as UP_FOR_RETRY. dag_id=spark_etl_minio_v14, task_id=spark_submit_task, execution_date=20230624T000000, start_date=20230625T061028, end_date=20230625T061029
[2023-06-25T06:10:29.757+0000] {standard_task_runner.py:100} ERROR - Failed to execute job 234 for task spark_submit_task (Cannot execute: spark-submit --master spark://spark:7077 --jars local:///opt/bitnami/spark/jars/hadoop-aws-3.2.0.jar,            local:///opt/bitnami/spark/jars/aws-java-sdk-bundle-1.11.375.jar --name arrow-spark /opt/***/dags/spark_etl_spark_minio.py. Error code is: 1.; 27779)
[2023-06-25T06:10:29.775+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-06-25T06:10:29.790+0000] {taskinstance.py:2585} INFO - 0 downstream tasks scheduled from follow-on schedule check
