[2023-06-25T06:21:14.143+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: spark_etl_minio_v16.spark_submit_task scheduled__2023-06-24T00:00:00+00:00 [queued]>
[2023-06-25T06:21:14.159+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: spark_etl_minio_v16.spark_submit_task scheduled__2023-06-24T00:00:00+00:00 [queued]>
[2023-06-25T06:21:14.160+0000] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-06-25T06:21:14.160+0000] {taskinstance.py:1283} INFO - Starting attempt 1 of 6
[2023-06-25T06:21:14.160+0000] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-06-25T06:21:14.172+0000] {taskinstance.py:1303} INFO - Executing <Task(SparkSubmitOperator): spark_submit_task> on 2023-06-24 00:00:00+00:00
[2023-06-25T06:21:14.177+0000] {standard_task_runner.py:55} INFO - Started process 29497 to run task
[2023-06-25T06:21:14.180+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'spark_etl_minio_v16', 'spark_submit_task', 'scheduled__2023-06-24T00:00:00+00:00', '--job-id', '246', '--raw', '--subdir', 'DAGS_FOLDER/spark_job_minio_v1.py', '--cfg-path', '/tmp/tmpdy5d2f43']
[2023-06-25T06:21:14.180+0000] {standard_task_runner.py:83} INFO - Job 246: Subtask spark_submit_task
[2023-06-25T06:21:14.193+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:250: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2023-06-25T06:21:14.211+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/sqlalchemy.py:124: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  return not conf.get("database", "sql_alchemy_conn").startswith("mssql")

[2023-06-25T06:21:14.242+0000] {task_command.py:388} INFO - Running <TaskInstance: spark_etl_minio_v16.spark_submit_task scheduled__2023-06-24T00:00:00+00:00 [running]> on host a8d69ab09d2d
[2023-06-25T06:21:14.331+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=spark_etl_minio_v16
AIRFLOW_CTX_TASK_ID=spark_submit_task
AIRFLOW_CTX_EXECUTION_DATE=2023-06-24T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-06-24T00:00:00+00:00
[2023-06-25T06:21:14.343+0000] {base.py:73} INFO - Using connection ID 'spark_conn' for task execution.
[2023-06-25T06:21:14.346+0000] {spark_submit.py:341} INFO - Spark-Submit cmd: spark-submit --master spark://spark:7077 --conf spark.hadoop.fs.s3a.aws.credentials.provider=org.apache.hadoop.fs.s3a.SimpleAWSCredentialsProvider --conf spark.hadoop.fs.s3a.path.style.access=true --conf spark.hadoop.fs.s3a.access.key=minioadmin --conf spark.hadoop.fs.s3a.secret.key=****** --conf spark.hadoop.fs.s3a.endpoint=http://minio:9000 --jars local:///opt/bitnami/spark/jars/hadoop-aws-3.2.0.jar,local:///opt/bitnami/spark/jars/aws-java-sdk-bundle-1.11.375.jar,local:///opt/bitnami/spark/jars/hadoop-common-3.2.0.jar --name arrow-spark /opt/***/dags/spark_etl_spark_minio.py
[2023-06-25T06:21:15.871+0000] {spark_submit.py:492} INFO - WARNING: An illegal reflective access operation has occurred
[2023-06-25T06:21:15.871+0000] {spark_submit.py:492} INFO - WARNING: Illegal reflective access by org.apache.spark.unsafe.Platform (file:/opt/spark/jars/spark-unsafe_2.12-3.2.0.jar) to constructor java.nio.DirectByteBuffer(long,int)
[2023-06-25T06:21:15.872+0000] {spark_submit.py:492} INFO - WARNING: Please consider reporting this to the maintainers of org.apache.spark.unsafe.Platform
[2023-06-25T06:21:15.872+0000] {spark_submit.py:492} INFO - WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
[2023-06-25T06:21:15.872+0000] {spark_submit.py:492} INFO - WARNING: All illegal access operations will be denied in a future release
[2023-06-25T06:21:16.214+0000] {spark_submit.py:492} INFO - Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
[2023-06-25T06:21:16.215+0000] {spark_submit.py:492} INFO - 23/06/25 06:21:16 WARN DependencyUtils: Local jar /opt/bitnami/spark/jars/hadoop-aws-3.2.0.jar does not exist, skipping.
[2023-06-25T06:21:16.215+0000] {spark_submit.py:492} INFO - 23/06/25 06:21:16 WARN DependencyUtils: Local jar /opt/bitnami/spark/jars/aws-java-sdk-bundle-1.11.375.jar does not exist, skipping.
[2023-06-25T06:21:16.215+0000] {spark_submit.py:492} INFO - 23/06/25 06:21:16 WARN DependencyUtils: Local jar /opt/bitnami/spark/jars/hadoop-common-3.2.0.jar does not exist, skipping.
[2023-06-25T06:21:17.087+0000] {spark_submit.py:492} INFO - 23/06/25 06:21:17 INFO SparkContext: Running Spark version 3.2.0
[2023-06-25T06:21:17.179+0000] {spark_submit.py:492} INFO - 23/06/25 06:21:17 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2023-06-25T06:21:17.343+0000] {spark_submit.py:492} INFO - 23/06/25 06:21:17 INFO ResourceUtils: ==============================================================
[2023-06-25T06:21:17.345+0000] {spark_submit.py:492} INFO - 23/06/25 06:21:17 INFO ResourceUtils: No custom resources configured for spark.driver.
[2023-06-25T06:21:17.346+0000] {spark_submit.py:492} INFO - 23/06/25 06:21:17 INFO ResourceUtils: ==============================================================
[2023-06-25T06:21:17.347+0000] {spark_submit.py:492} INFO - 23/06/25 06:21:17 INFO SparkContext: Submitted application: arrow-spark
[2023-06-25T06:21:17.383+0000] {spark_submit.py:492} INFO - 23/06/25 06:21:17 INFO ResourceProfile: Default ResourceProfile created, executor resources: Map(cores -> name: cores, amount: 1, script: , vendor: , memory -> name: memory, amount: 1024, script: , vendor: , offHeap -> name: offHeap, amount: 0, script: , vendor: ), task resources: Map(cpus -> name: cpus, amount: 1.0)
[2023-06-25T06:21:17.400+0000] {spark_submit.py:492} INFO - 23/06/25 06:21:17 INFO ResourceProfile: Limiting resource is cpu
[2023-06-25T06:21:17.400+0000] {spark_submit.py:492} INFO - 23/06/25 06:21:17 INFO ResourceProfileManager: Added ResourceProfile id: 0
[2023-06-25T06:21:17.469+0000] {spark_submit.py:492} INFO - 23/06/25 06:21:17 INFO SecurityManager: Changing view acls to: default
[2023-06-25T06:21:17.469+0000] {spark_submit.py:492} INFO - 23/06/25 06:21:17 INFO SecurityManager: Changing modify acls to: default
[2023-06-25T06:21:17.470+0000] {spark_submit.py:492} INFO - 23/06/25 06:21:17 INFO SecurityManager: Changing view acls groups to:
[2023-06-25T06:21:17.470+0000] {spark_submit.py:492} INFO - 23/06/25 06:21:17 INFO SecurityManager: Changing modify acls groups to:
[2023-06-25T06:21:17.471+0000] {spark_submit.py:492} INFO - 23/06/25 06:21:17 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users  with view permissions: Set(default); groups with view permissions: Set(); users  with modify permissions: Set(default); groups with modify permissions: Set()
[2023-06-25T06:21:17.745+0000] {spark_submit.py:492} INFO - 23/06/25 06:21:17 INFO Utils: Successfully started service 'sparkDriver' on port 39059.
[2023-06-25T06:21:17.790+0000] {spark_submit.py:492} INFO - 23/06/25 06:21:17 INFO SparkEnv: Registering MapOutputTracker
[2023-06-25T06:21:17.859+0000] {spark_submit.py:492} INFO - 23/06/25 06:21:17 INFO SparkEnv: Registering BlockManagerMaster
[2023-06-25T06:21:17.893+0000] {spark_submit.py:492} INFO - 23/06/25 06:21:17 INFO BlockManagerMasterEndpoint: Using org.apache.spark.storage.DefaultTopologyMapper for getting topology information
[2023-06-25T06:21:17.894+0000] {spark_submit.py:492} INFO - 23/06/25 06:21:17 INFO BlockManagerMasterEndpoint: BlockManagerMasterEndpoint up
[2023-06-25T06:21:17.899+0000] {spark_submit.py:492} INFO - 23/06/25 06:21:17 INFO SparkEnv: Registering BlockManagerMasterHeartbeat
[2023-06-25T06:21:17.929+0000] {spark_submit.py:492} INFO - 23/06/25 06:21:17 INFO DiskBlockManager: Created local directory at /tmp/blockmgr-b2ed7490-f0e2-49a4-ac25-545f29d9fbbd
[2023-06-25T06:21:17.952+0000] {spark_submit.py:492} INFO - 23/06/25 06:21:17 INFO MemoryStore: MemoryStore started with capacity 434.4 MiB
[2023-06-25T06:21:17.971+0000] {spark_submit.py:492} INFO - 23/06/25 06:21:17 INFO SparkEnv: Registering OutputCommitCoordinator
[2023-06-25T06:21:18.311+0000] {spark_submit.py:492} INFO - 23/06/25 06:21:18 WARN Utils: Service 'SparkUI' could not bind on port 4040. Attempting port 4041.
[2023-06-25T06:21:18.313+0000] {spark_submit.py:492} INFO - 23/06/25 06:21:18 WARN Utils: Service 'SparkUI' could not bind on port 4041. Attempting port 4042.
[2023-06-25T06:21:18.314+0000] {spark_submit.py:492} INFO - 23/06/25 06:21:18 WARN Utils: Service 'SparkUI' could not bind on port 4042. Attempting port 4043.
[2023-06-25T06:21:18.315+0000] {spark_submit.py:492} INFO - 23/06/25 06:21:18 WARN Utils: Service 'SparkUI' could not bind on port 4043. Attempting port 4044.
[2023-06-25T06:21:18.316+0000] {spark_submit.py:492} INFO - 23/06/25 06:21:18 WARN Utils: Service 'SparkUI' could not bind on port 4044. Attempting port 4045.
[2023-06-25T06:21:18.329+0000] {spark_submit.py:492} INFO - 23/06/25 06:21:18 WARN Utils: Service 'SparkUI' could not bind on port 4045. Attempting port 4046.
[2023-06-25T06:21:18.329+0000] {spark_submit.py:492} INFO - 23/06/25 06:21:18 WARN Utils: Service 'SparkUI' could not bind on port 4046. Attempting port 4047.
[2023-06-25T06:21:18.329+0000] {spark_submit.py:492} INFO - 23/06/25 06:21:18 WARN Utils: Service 'SparkUI' could not bind on port 4047. Attempting port 4048.
[2023-06-25T06:21:18.330+0000] {spark_submit.py:492} INFO - 23/06/25 06:21:18 WARN Utils: Service 'SparkUI' could not bind on port 4048. Attempting port 4049.
[2023-06-25T06:21:18.330+0000] {spark_submit.py:492} INFO - 23/06/25 06:21:18 WARN Utils: Service 'SparkUI' could not bind on port 4049. Attempting port 4050.
[2023-06-25T06:21:18.330+0000] {spark_submit.py:492} INFO - 23/06/25 06:21:18 WARN Utils: Service 'SparkUI' could not bind on port 4050. Attempting port 4051.
[2023-06-25T06:21:18.330+0000] {spark_submit.py:492} INFO - 23/06/25 06:21:18 WARN Utils: Service 'SparkUI' could not bind on port 4051. Attempting port 4052.
[2023-06-25T06:21:18.330+0000] {spark_submit.py:492} INFO - 23/06/25 06:21:18 WARN Utils: Service 'SparkUI' could not bind on port 4052. Attempting port 4053.
[2023-06-25T06:21:18.330+0000] {spark_submit.py:492} INFO - 23/06/25 06:21:18 WARN Utils: Service 'SparkUI' could not bind on port 4053. Attempting port 4054.
[2023-06-25T06:21:18.343+0000] {spark_submit.py:492} INFO - 23/06/25 06:21:18 INFO Utils: Successfully started service 'SparkUI' on port 4054.
[2023-06-25T06:21:18.536+0000] {spark_submit.py:492} INFO - 23/06/25 06:21:18 INFO SparkUI: Bound SparkUI to 0.0.0.0, and started at http://a8d69ab09d2d:4054
[2023-06-25T06:21:18.556+0000] {spark_submit.py:492} INFO - 23/06/25 06:21:18 INFO SparkContext: Added JAR local:///opt/bitnami/spark/jars/hadoop-aws-3.2.0.jar at file:/opt/bitnami/spark/jars/hadoop-aws-3.2.0.jar with timestamp 1687674077077
[2023-06-25T06:21:18.556+0000] {spark_submit.py:492} INFO - 23/06/25 06:21:18 INFO SparkContext: Added JAR local:///opt/bitnami/spark/jars/aws-java-sdk-bundle-1.11.375.jar at file:/opt/bitnami/spark/jars/aws-java-sdk-bundle-1.11.375.jar with timestamp 1687674077077
[2023-06-25T06:21:18.557+0000] {spark_submit.py:492} INFO - 23/06/25 06:21:18 INFO SparkContext: Added JAR local:///opt/bitnami/spark/jars/hadoop-common-3.2.0.jar at file:/opt/bitnami/spark/jars/hadoop-common-3.2.0.jar with timestamp 1687674077077
[2023-06-25T06:21:18.830+0000] {spark_submit.py:492} INFO - 23/06/25 06:21:18 INFO StandaloneAppClient$ClientEndpoint: Connecting to master spark://spark:7077...
[2023-06-25T06:21:18.963+0000] {spark_submit.py:492} INFO - 23/06/25 06:21:18 INFO TransportClientFactory: Successfully created connection to spark/172.19.0.11:7077 after 51 ms (0 ms spent in bootstraps)
[2023-06-25T06:21:19.366+0000] {spark_submit.py:492} INFO - 23/06/25 06:21:19 INFO StandaloneSchedulerBackend: Connected to Spark cluster with app ID app-20230625062119-0001
[2023-06-25T06:21:19.392+0000] {spark_submit.py:492} INFO - 23/06/25 06:21:19 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 39409.
[2023-06-25T06:21:19.393+0000] {spark_submit.py:492} INFO - 23/06/25 06:21:19 INFO NettyBlockTransferService: Server created on a8d69ab09d2d:39409
[2023-06-25T06:21:19.394+0000] {spark_submit.py:492} INFO - 23/06/25 06:21:19 INFO BlockManager: Using org.apache.spark.storage.RandomBlockReplicationPolicy for block replication policy
[2023-06-25T06:21:19.423+0000] {spark_submit.py:492} INFO - 23/06/25 06:21:19 INFO BlockManagerMaster: Registering BlockManager BlockManagerId(driver, a8d69ab09d2d, 39409, None)
[2023-06-25T06:21:19.432+0000] {spark_submit.py:492} INFO - 23/06/25 06:21:19 INFO BlockManagerMasterEndpoint: Registering block manager a8d69ab09d2d:39409 with 434.4 MiB RAM, BlockManagerId(driver, a8d69ab09d2d, 39409, None)
[2023-06-25T06:21:19.447+0000] {spark_submit.py:492} INFO - 23/06/25 06:21:19 INFO BlockManagerMaster: Registered BlockManager BlockManagerId(driver, a8d69ab09d2d, 39409, None)
[2023-06-25T06:21:19.449+0000] {spark_submit.py:492} INFO - 23/06/25 06:21:19 INFO BlockManager: Initialized BlockManager: BlockManagerId(driver, a8d69ab09d2d, 39409, None)
[2023-06-25T06:21:19.700+0000] {spark_submit.py:492} INFO - 23/06/25 06:21:19 INFO StandaloneSchedulerBackend: SchedulerBackend is ready for scheduling beginning after reached minRegisteredResourcesRatio: 0.0
[2023-06-25T06:21:20.047+0000] {spark_submit.py:492} INFO - 23/06/25 06:21:20 INFO SharedState: Setting hive.metastore.warehouse.dir ('null') to the value of spark.sql.warehouse.dir.
[2023-06-25T06:21:20.075+0000] {spark_submit.py:492} INFO - 23/06/25 06:21:20 INFO SharedState: Warehouse path is 'file:/opt/***/spark-warehouse'.
[2023-06-25T06:21:49.360+0000] {base_job.py:243} ERROR - LocalTaskJob heartbeat got an exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3361, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 691, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/create.py", line 578, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "postgres" to address: Temporary failure in name resolution


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/jobs/base_job.py", line 239, in heartbeat
    self.heartbeat_callback(session=session)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/session.py", line 72, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/jobs/local_task_job.py", line 231, in heartbeat_callback
    self.task_instance.refresh_from_db()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/session.py", line 75, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 792, in refresh_from_db
    ti = qry.one_or_none()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 2850, in one_or_none
    return self._iter().one_or_none()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 2916, in _iter
    result = self.session.execute(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1713, in execute
    conn = self._connection_for_bind(bind)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1552, in _connection_for_bind
    return self._transaction._connection_for_bind(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 747, in _connection_for_bind
    conn = bind.connect()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3315, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3394, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3364, in _wrap_pool_connect
    Connection._handle_dbapi_exception_noconnection(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2198, in _handle_dbapi_exception_noconnection
    util.raise_(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3361, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 691, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/create.py", line 578, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not translate host name "postgres" to address: Temporary failure in name resolution

(Background on this error at: https://sqlalche.me/e/14/e3q8)
